---
title: "Analysis of the Pellicci gamma-delta T-cell data set"
description: |
author:
  - name: Peter Hickey 
    url: https://peterhickey.org
    affiliation: Single Cell Open Research Endeavour (SCORE), WEHI
    affiliation_url: https://www.wehi.edu.au/people/shalin-naik/3310/score
  - name: William Ho
    affiliation: Single Cell Open Research Endeavour (SCORE), WEHI
    affiliation_url: https://www.wehi.edu.au/people/rory-bowden/4536/wehi-advanced-genomics-facility
date: "`r Sys.Date()`"
bibliography: ref.bib
---

# Overview

Analysis accompanying paper '**Human Vγ9Vδ2+ T cells develop within the postnatal thymus via a three-stage pathway defined by distinct molecular and cellular changes**'.
Please see [https://wehiscore.github.io/C094_Pellicci](https://wehiscore.github.io/C094_Pellicci) for the HTML version of this analysis report.

After sequencing, expression was quantified by counting the number of UMIs mapped to each gene using scPipe [@tian2018scpipe]; see [`code/scPipe.R`](../code/scPipe.R).
Count data for all endogenous genes (GENCODE Release vM18: GRCm38.p6) and spike-in transcripts (ERCC) are available in this repository.

This analysis is adapted from the `r BiocStyle::Biocpkg("simpleSingleCell")` workflow as well as the [**Orchestrating Single-Cell Analysis with Bioconductor book**](https://osca.bioconductor.org).

This analysis is adapted from the [**Orchestrating Single-Cell Analysis with Bioconductor book**](https://osca.bioconductor.org).

# Analysis version information  {.appendix}

**R version**: `r R.version.string`

**Bioconductor version**: `r BiocManager::version()`
